### ISSUE TITLE
Slide-In Prompt to Delete a Task

### ISSUE THREAD

**Issue by sarthakps** [sarthakps/to-do#5]
Currently, to delete a task, the user has to swipe the task to the left. There is no confirmation prompt before the task is deleted. Also, there is no option to undo the action.

The aim is to-
* Provide a prompt as shown below on swiping a task to the left. Which will make deletion a two-step process and will help eliminate accidental deletes.

![and](https://user-images.githubusercontent.com/45737914/92916944-a0757c00-f44b-11ea-8b47-c700c6e204e6.jpg)

**Comment by Khushank1120** [comment]
I would like to work on this issue.

**Comment by sarthakps** [comment]
give @rasacharjee 75 points
