### ISSUE TITLE
Replace Hardcoded Strings by @string Resources

### ISSUE THREAD

**Issue by sarthakps** [sarthakps/to-do#6]
The current implementation utilizes hardcoded strings to generate texts to be displayed to the user.

The aim is to-
* Replace/Minimize all the occurrences of hardcoded strings by repalcing them with string resources.

**Comment by rasacharjee** [comment]
@sarthakps sir  can I work on the issue

**Comment by sarthakps** [comment]
Of course. Contributions in any capacity are welcome and appreciated.
